apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: hatena-intern-2021
build:
  artifacts:
  - image: 982861970286.dkr.ecr.ap-northeast-1.amazonaws.com/hatena-intern-2021-account
    context: services/account
  # - image: hatena-intern-2021-account-test
  #   context: services/account
  #   docker:
  #     dockerfile: Dockerfile.test
  - image: 982861970286.dkr.ecr.ap-northeast-1.amazonaws.com/hatena-intern-2021-blog
    context: services/blog
  # - image: hatena-intern-2021-blog-test
  #   context: services/blog
  #   docker:
  #     dockerfile: Dockerfile.test
  - image: 982861970286.dkr.ecr.ap-northeast-1.amazonaws.com/hatena-intern-2021-renderer-go
    context: services/renderer-go
  - image: hatena-intern-2021-fetcher
    context: services/fetcher
  local:
    push: true
    useBuildkit: true
deploy:
  statusCheckDeadlineSeconds: 180
  kubeContext: hatena-intern-2021
  kustomize:
    paths:
    - k8s
